/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileProfileRouteImport } from './routes/profile/profile'
import { Route as HomePageHomePageOutRouteImport } from './routes/homePage/homePageOut'
import { Route as HomePageHomePageInRouteImport } from './routes/homePage/homePageIn'
import { Route as AuthSignUpRouteImport } from './routes/auth/signUp'
import { Route as AuthSignInRouteImport } from './routes/auth/signIn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileRoute = ProfileProfileRouteImport.update({
  id: '/profile/profile',
  path: '/profile/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomePageHomePageOutRoute = HomePageHomePageOutRouteImport.update({
  id: '/homePage/homePageOut',
  path: '/homePage/homePageOut',
  getParentRoute: () => rootRouteImport,
} as any)
const HomePageHomePageInRoute = HomePageHomePageInRouteImport.update({
  id: '/homePage/homePageIn',
  path: '/homePage/homePageIn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/signUp',
  path: '/auth/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/signIn',
  path: '/auth/signIn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/signIn': typeof AuthSignInRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/homePage/homePageIn': typeof HomePageHomePageInRoute
  '/homePage/homePageOut': typeof HomePageHomePageOutRoute
  '/profile/profile': typeof ProfileProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signIn': typeof AuthSignInRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/homePage/homePageIn': typeof HomePageHomePageInRoute
  '/homePage/homePageOut': typeof HomePageHomePageOutRoute
  '/profile/profile': typeof ProfileProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/signIn': typeof AuthSignInRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/homePage/homePageIn': typeof HomePageHomePageInRoute
  '/homePage/homePageOut': typeof HomePageHomePageOutRoute
  '/profile/profile': typeof ProfileProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/homePage/homePageIn'
    | '/homePage/homePageOut'
    | '/profile/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/homePage/homePageIn'
    | '/homePage/homePageOut'
    | '/profile/profile'
  id:
    | '__root__'
    | '/'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/homePage/homePageIn'
    | '/homePage/homePageOut'
    | '/profile/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  HomePageHomePageInRoute: typeof HomePageHomePageInRoute
  HomePageHomePageOutRoute: typeof HomePageHomePageOutRoute
  ProfileProfileRoute: typeof ProfileProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/profile': {
      id: '/profile/profile'
      path: '/profile/profile'
      fullPath: '/profile/profile'
      preLoaderRoute: typeof ProfileProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homePage/homePageOut': {
      id: '/homePage/homePageOut'
      path: '/homePage/homePageOut'
      fullPath: '/homePage/homePageOut'
      preLoaderRoute: typeof HomePageHomePageOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homePage/homePageIn': {
      id: '/homePage/homePageIn'
      path: '/homePage/homePageIn'
      fullPath: '/homePage/homePageIn'
      preLoaderRoute: typeof HomePageHomePageInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signUp': {
      id: '/auth/signUp'
      path: '/auth/signUp'
      fullPath: '/auth/signUp'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signIn': {
      id: '/auth/signIn'
      path: '/auth/signIn'
      fullPath: '/auth/signIn'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  HomePageHomePageInRoute: HomePageHomePageInRoute,
  HomePageHomePageOutRoute: HomePageHomePageOutRoute,
  ProfileProfileRoute: ProfileProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
